# Generated by Django 3.2 on 2022-06-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('contact', '0002_auto_20220515_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
